name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # 监听 main 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./default  # 关键：指定你的网站源码文件夹
          publish_branch: gh-pages # 部署到的分支